name: deploy-payments

on:
  push:
    branches:
      - master
    paths:
      - 'ticketing/payments/**'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing/payments && docker build -t azakaryan/payments .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push azakaryan/payments
      # Here should go the actual deployment script to the cluster running in a cloud.
